languageCode = 'en-us'
title = 'Sourcemeta'
staticDir = [ './vendor/bootstrap-icons/font/fonts', './static' ]

[Params]
description = 'A growing library of battle-tested JSON Schemas implementing standards from ISO, IETF, IEC, W3C, XBRL, and more. Ready to plug into your OpenAPI specs and API Gateways'

[markup]
  [markup.highlight]
    style = 'swapoff'

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "vendor/bootstrap/js"
target = "assets/vendor/bootstrap/js"
